---
- name: install necessary packages to execute lxc commands
  pip: name=lxc-python2
  tags: running

- name: install necessary packages to execute lxc commands
  apt:
    name:
      - lxc
  tags: running

- name: Add sudoers to host
  copy: src=sudoers  dest=/etc/sudoers owner=root group=root  mode=644

- name: create container and add user and key
  lxc_container:
    name: "{{ names }}"
    container_log: true
    template: ubuntu
    state: started
    template_options: --release {{ release }}
  tags: running

- name: Start {{ names }} container
  lxc_container:
    name: "{{ names }}"
    state: started
  tags: running

- name: copy template sources.list
  template: src=sources.list dest=/var/lib/lxc/{{ names }}/rootfs/etc/apt/sources.list owner=root group=root mode="0644"
  tags: running

- name: defining Templates
  template: src=templates/{{item}}.conf.j2 dest=/usr/share/lxc/config/{{item}}.conf mode=0644 owner=root group=root
  with_items:
    - default
    - basic
  tags: templates

- name: install {{ names }} minimal requirements to work with ansible
  lxc_container:
    name: "{{ names }}"
    container_command: |
      deluser ubuntu &&  adduser -disabled-password --gecos ""  --gid {{ user_botgid }}  {{ user_bot }}
      addgroup admin -gid 12000
      useradd {{ user_bot }} -s /bin/bash -m -U
      echo -e "tempass\ntempass" | passwd {{ user_bot }}
      mkdir /home/{{ user_botgid }}/.ssh
      adduser {{ user_bot }} admin
    container_config:
      - lxc.include = /usr/share/lxc/config/{{template}}.conf
  tags: running




- name: Add sudoers
  copy: src=sudoers  dest=/var/lib/lxc/{{ names }}/rootfs/etc/sudoers owner=root group=root mode=644

- name: add authorized_keys to {{ names }}
  file: path=/var/lib/lxc/{{ names }}/rootfs/home/ubuntu state=absent
  tags: running

- name: add authorized_keys to {{ names }}
  file: path=/var/lib/lxc/{{ names }}/rootfs/home/agalan/.ssh/ mode=0700  owner={{ user_bot }} group={{ user_botgid }} state=directory
  tags: running

- name: Copy SSH key to {{ names }}
  copy: src=files/key dest=/var/lib/lxc/{{ names }}/rootfs/home/agalan/.ssh/authorized_keys mode=0600  owner={{ user_bot }} group={{ user_botgid }}
  tags: running

- debug:
   msg: do if necessary ssh {{user_bot}}@{{ names }}.lxc 'sudo apt-get update'
  tags: running

- name: install minimal requirements in {{ names }}
  become_user: agalan
  command: ssh {{ names }}.lxc "sudo apt -y install python-simplejson"
  tags: running
